package com.smvis123.api

const val BASE_URL = "https://appbazooka.com/dashboard/index.php/api/"
const val IMAGE_BASE_URL = "https://appbazooka.com/dashboard/"
const val UNIQUE_ID = "unique_id"
const val UNIQUE_ID_VALUE = "e12bdc88419fe1a6e"
const val API_IMAGE_SLIDER = "image_sliders"
const val API_VIDEO_CATEGORY = "vidcats"
const val API_VIDEO_CATEGORY_ID = "video_cat_id"
const val API_VIDEO_CATEGORY_DATA = "vidcat/{$API_VIDEO_CATEGORY_ID}"
const val API_LIVE_TV = "livetv"
const val API_SCHEDULE = "schedule_newversion"
const val API_GALLERY_ALBUMS = "albums_new"
const val API_GALLERY_ALBUM_ID = "id"
const val API_GALLERY_ALBUM_IMAGES = "album/{$API_GALLERY_ALBUM_ID}"
const val API_PREACHERS = "getPastorlist"